// Copyright (c) 2016 The Chromium Embedded Framework Authors. All rights
// reserved. Use of this source code is governed by a BSD-style license that
// can be found in the LICENSE file.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the CEF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//

#ifndef CEF_LIBCEF_DLL_CTOCPP_DOMDOCUMENT_CTOCPP_H_
#define CEF_LIBCEF_DLL_CTOCPP_DOMDOCUMENT_CTOCPP_H_
#pragma once

#ifndef USING_CEF_SHARED
#pragma message("Warning: "__FILE__" may be accessed wrapper-side only")
#else  // USING_CEF_SHARED

#include "include/cef_dom.h"
#include "include/capi/cef_dom_capi.h"
#include "libcef_dll/ctocpp/ctocpp.h"

// Wrap a C structure with a C++ class.
// This class may be instantiated and accessed wrapper-side only.
class CefDOMDocumentCToCpp
    : public CefCToCpp<CefDOMDocumentCToCpp, CefDOMDocument,
        cef_domdocument_t> {
 public:
  CefDOMDocumentCToCpp();

  // CefDOMDocument methods.
  Type GetType() OVERRIDE;
  CefRefPtr<CefDOMNode> GetDocument() OVERRIDE;
  CefRefPtr<CefDOMNode> GetBody() OVERRIDE;
  CefRefPtr<CefDOMNode> GetHead() OVERRIDE;
  CefString GetTitle() OVERRIDE;
  CefRefPtr<CefDOMNode> GetElementById(const CefString& id) OVERRIDE;
  CefRefPtr<CefDOMNode> GetFocusedNode() OVERRIDE;
  bool HasSelection() OVERRIDE;
  int GetSelectionStartOffset() OVERRIDE;
  int GetSelectionEndOffset() OVERRIDE;
  CefString GetSelectionAsMarkup() OVERRIDE;
  CefString GetSelectionAsText() OVERRIDE;
  CefString GetBaseURL() OVERRIDE;
  CefString GetCompleteURL(const CefString& partialURL) OVERRIDE;
};

#endif  // USING_CEF_SHARED
#endif  // CEF_LIBCEF_DLL_CTOCPP_DOMDOCUMENT_CTOCPP_H_
