// Copyright (c) 2016 The Chromium Embedded Framework Authors. All rights
// reserved. Use of this source code is governed by a BSD-style license that
// can be found in the LICENSE file.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the CEF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//

#ifndef CEF_LIBCEF_DLL_CTOCPP_LIST_VALUE_CTOCPP_H_
#define CEF_LIBCEF_DLL_CTOCPP_LIST_VALUE_CTOCPP_H_
#pragma once

#ifndef USING_CEF_SHARED
#pragma message("Warning: "__FILE__" may be accessed wrapper-side only")
#else  // USING_CEF_SHARED

#include "include/cef_values.h"
#include "include/capi/cef_values_capi.h"
#include "libcef_dll/ctocpp/ctocpp.h"

// Wrap a C structure with a C++ class.
// This class may be instantiated and accessed wrapper-side only.
class CefListValueCToCpp
    : public CefCToCpp<CefListValueCToCpp, CefListValue, cef_list_value_t> {
 public:
  CefListValueCToCpp();

  // CefListValue methods.
  bool IsValid() OVERRIDE;
  bool IsOwned() OVERRIDE;
  bool IsReadOnly() OVERRIDE;
  bool IsSame(CefRefPtr<CefListValue> that) OVERRIDE;
  bool IsEqual(CefRefPtr<CefListValue> that) OVERRIDE;
  CefRefPtr<CefListValue> Copy() OVERRIDE;
  bool SetSize(size_t size) OVERRIDE;
  size_t GetSize() OVERRIDE;
  bool Clear() OVERRIDE;
  bool Remove(int index) OVERRIDE;
  CefValueType GetType(int index) OVERRIDE;
  CefRefPtr<CefValue> GetValue(int index) OVERRIDE;
  bool GetBool(int index) OVERRIDE;
  int GetInt(int index) OVERRIDE;
  double GetDouble(int index) OVERRIDE;
  CefString GetString(int index) OVERRIDE;
  CefRefPtr<CefBinaryValue> GetBinary(int index) OVERRIDE;
  CefRefPtr<CefDictionaryValue> GetDictionary(int index) OVERRIDE;
  CefRefPtr<CefListValue> GetList(int index) OVERRIDE;
  bool SetValue(int index, CefRefPtr<CefValue> value) OVERRIDE;
  bool SetNull(int index) OVERRIDE;
  bool SetBool(int index, bool value) OVERRIDE;
  bool SetInt(int index, int value) OVERRIDE;
  bool SetDouble(int index, double value) OVERRIDE;
  bool SetString(int index, const CefString& value) OVERRIDE;
  bool SetBinary(int index, CefRefPtr<CefBinaryValue> value) OVERRIDE;
  bool SetDictionary(int index, CefRefPtr<CefDictionaryValue> value) OVERRIDE;
  bool SetList(int index, CefRefPtr<CefListValue> value) OVERRIDE;
};

#endif  // USING_CEF_SHARED
#endif  // CEF_LIBCEF_DLL_CTOCPP_LIST_VALUE_CTOCPP_H_
