// Copyright (c) 2015 The Chromium Embedded Framework Authors. All rights
// reserved. Use of this source code is governed by a BSD-style license that
// can be found in the LICENSE file.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the CEF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//

#include "libcef_dll/ctocpp/auth_callback_ctocpp.h"


// VIRTUAL METHODS - Body may be edited by hand.

void CefAuthCallbackCToCpp::Continue(const CefString& username,
    const CefString& password) {
  cef_auth_callback_t* _struct = GetStruct();
  if (CEF_MEMBER_MISSING(_struct, cont))
    return;

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Verify param: username; type: string_byref_const
  DCHECK(!username.empty());
  if (username.empty())
    return;
  // Verify param: password; type: string_byref_const
  DCHECK(!password.empty());
  if (password.empty())
    return;

  // Execute
  _struct->cont(_struct,
      username.GetStruct(),
      password.GetStruct());
}

void CefAuthCallbackCToCpp::Cancel() {
  cef_auth_callback_t* _struct = GetStruct();
  if (CEF_MEMBER_MISSING(_struct, cancel))
    return;

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  _struct->cancel(_struct);
}


// CONSTRUCTOR - Do not edit by hand.

CefAuthCallbackCToCpp::CefAuthCallbackCToCpp() {
}

template<> cef_auth_callback_t* CefCToCpp<CefAuthCallbackCToCpp,
    CefAuthCallback, cef_auth_callback_t>::UnwrapDerived(CefWrapperType type,
    CefAuthCallback* c) {
  NOTREACHED() << "Unexpected class type: " << type;
  return NULL;
}

#ifndef NDEBUG
template<> base::AtomicRefCount CefCToCpp<CefAuthCallbackCToCpp,
    CefAuthCallback, cef_auth_callback_t>::DebugObjCt = 0;
#endif

template<> CefWrapperType CefCToCpp<CefAuthCallbackCToCpp, CefAuthCallback,
    cef_auth_callback_t>::kWrapperType = WT_AUTH_CALLBACK;
