// Copyright (c) 2015 The Chromium Embedded Framework Authors. All rights
// reserved. Use of this source code is governed by a BSD-style license that
// can be found in the LICENSE file.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the CEF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//

#include "libcef_dll/ctocpp/download_item_callback_ctocpp.h"


// VIRTUAL METHODS - Body may be edited by hand.

void CefDownloadItemCallbackCToCpp::Cancel() {
  cef_download_item_callback_t* _struct = GetStruct();
  if (CEF_MEMBER_MISSING(_struct, cancel))
    return;

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  _struct->cancel(_struct);
}

void CefDownloadItemCallbackCToCpp::Pause() {
  cef_download_item_callback_t* _struct = GetStruct();
  if (CEF_MEMBER_MISSING(_struct, pause))
    return;

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  _struct->pause(_struct);
}

void CefDownloadItemCallbackCToCpp::Resume() {
  cef_download_item_callback_t* _struct = GetStruct();
  if (CEF_MEMBER_MISSING(_struct, resume))
    return;

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  _struct->resume(_struct);
}


// CONSTRUCTOR - Do not edit by hand.

CefDownloadItemCallbackCToCpp::CefDownloadItemCallbackCToCpp() {
}

template<> cef_download_item_callback_t* CefCToCpp<CefDownloadItemCallbackCToCpp,
    CefDownloadItemCallback, cef_download_item_callback_t>::UnwrapDerived(
    CefWrapperType type, CefDownloadItemCallback* c) {
  NOTREACHED() << "Unexpected class type: " << type;
  return NULL;
}

#ifndef NDEBUG
template<> base::AtomicRefCount CefCToCpp<CefDownloadItemCallbackCToCpp,
    CefDownloadItemCallback, cef_download_item_callback_t>::DebugObjCt = 0;
#endif

template<> CefWrapperType CefCToCpp<CefDownloadItemCallbackCToCpp,
    CefDownloadItemCallback, cef_download_item_callback_t>::kWrapperType =
    WT_DOWNLOAD_ITEM_CALLBACK;
