// Copyright (c) 2015 The Chromium Embedded Framework Authors. All rights
// reserved. Use of this source code is governed by a BSD-style license that
// can be found in the LICENSE file.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the CEF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//

#ifndef CEF_LIBCEF_DLL_CTOCPP_SSLCERT_PRINCIPAL_CTOCPP_H_
#define CEF_LIBCEF_DLL_CTOCPP_SSLCERT_PRINCIPAL_CTOCPP_H_
#pragma once

#ifndef USING_CEF_SHARED
#pragma message("Warning: "__FILE__" may be accessed wrapper-side only")
#else  // USING_CEF_SHARED

#include <vector>
#include "include/cef_ssl_info.h"
#include "include/capi/cef_ssl_info_capi.h"
#include "libcef_dll/ctocpp/ctocpp.h"

// Wrap a C structure with a C++ class.
// This class may be instantiated and accessed wrapper-side only.
class CefSSLCertPrincipalCToCpp
    : public CefCToCpp<CefSSLCertPrincipalCToCpp, CefSSLCertPrincipal,
        cef_sslcert_principal_t> {
 public:
  CefSSLCertPrincipalCToCpp();

  // CefSSLCertPrincipal methods.
  CefString GetDisplayName() OVERRIDE;
  CefString GetCommonName() OVERRIDE;
  CefString GetLocalityName() OVERRIDE;
  CefString GetStateOrProvinceName() OVERRIDE;
  CefString GetCountryName() OVERRIDE;
  void GetStreetAddresses(std::vector<CefString>& addresses) OVERRIDE;
  void GetOrganizationNames(std::vector<CefString>& names) OVERRIDE;
  void GetOrganizationUnitNames(std::vector<CefString>& names) OVERRIDE;
  void GetDomainComponents(std::vector<CefString>& components) OVERRIDE;
};

#endif  // USING_CEF_SHARED
#endif  // CEF_LIBCEF_DLL_CTOCPP_SSLCERT_PRINCIPAL_CTOCPP_H_
